// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/4/20 14:59:49
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/futuristic-blog/frontend-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/futuristic-blog/frontend-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/futuristic-blog/frontend-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/futuristic-blog/frontend-nuxt/plugins/**/*.{js,ts,mjs}","C:/futuristic-blog/frontend-nuxt/composables/**/*.{js,ts,mjs}","C:/futuristic-blog/frontend-nuxt/utils/**/*.{js,ts,mjs}","C:/futuristic-blog/frontend-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/futuristic-blog/frontend-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/futuristic-blog/frontend-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/futuristic-blog/frontend-nuxt/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;